stages:
  - deploy

variables:
  VERCEL_TOKEN: ${VERCEL_TOKEN}

deploy_to_vercel:
  stage: deploy
  image: node:16
  before_script:
    - curl -fsSL https://bun.sh/install | bash
    - export PATH="$HOME/.bun/bin:$PATH"
  script:
    - bun install
    - bun run build
    - npx vercel --token $VERCEL_TOKEN --prod
  only:
    - main
