stages:
  - lint
  - test
  - code_quality

variables:
  NODE_ENV: 'development'

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

before_script:
  - npm install

lint:
  stage: lint
  script:
    - npm run lint

test:
  stage: test
  script:
    - npm test

include:
  - local: '/.gitlab-ci-code-quality.yml'
